export const ENTRY_ANNOTATION_AUTO_COMPLETE_DELAY_MS = 3000;
export const DAY_TRANSITION_ANNOTATION_AUTO_COMPLETE_DELAY_MS = 4000;
export const DAY_TRANSITION_UI_FADE_OUT_DELAY_MS = 1000;
export const DAY_TRANSITION_EYE_CLOSED_PAUSE_MS = 500;
export const DAY_TRANSITION_GAME_UI_REVEAL_DELAY_MS = 3000;
export const MENU_OPENING_TRANSITION_DELAY_MS = 400;
export const QUESTIONNAIRE_ENTRY_DELAY_MS = 1000;
export const HSP_QUESTIONNAIRE_CONTENT_READY_DELAY_MS = 2000;
